USE [AdventureworksDW2016CTP3]
GO


CREATE TABLE [dbo].[FactResellerSales_Heap](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[ResellerKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NULL,
	[OrderQuantity] [smallint] NULL,
	[UnitPrice] [money] NULL,
	[ExtendedAmount] [money] NULL,
	[UnitPriceDiscountPct] [float] NULL,
	[DiscountAmount] [float] NULL,
	[ProductStandardCost] [money] NULL,
	[TotalProductCost] [money] NULL,
	[SalesAmount] [money] NULL,
	[TaxAmt] [money] NULL,
	[Freight] [money] NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL)


CREATE TABLE [dbo].[FactResellerSales_CI](
	[ProductKey] [int] NOT NULL,
	[OrderDateKey] [int] NOT NULL,
	[DueDateKey] [int] NOT NULL,
	[ShipDateKey] [int] NOT NULL,
	[ResellerKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionKey] [int] NOT NULL,
	[CurrencyKey] [int] NOT NULL,
	[SalesTerritoryKey] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](20) NOT NULL,
	[SalesOrderLineNumber] [tinyint] NOT NULL,
	[RevisionNumber] [tinyint] NULL,
	[OrderQuantity] [smallint] NULL,
	[UnitPrice] [money] NULL,
	[ExtendedAmount] [money] NULL,
	[UnitPriceDiscountPct] [float] NULL,
	[DiscountAmount] [float] NULL,
	[ProductStandardCost] [money] NULL,
	[TotalProductCost] [money] NULL,
	[SalesAmount] [money] NULL,
	[TaxAmt] [money] NULL,
	[Freight] [money] NULL,
	[CarrierTrackingNumber] [nvarchar](25) NULL,
	[CustomerPONumber] [nvarchar](25) NULL,
	[OrderDate] [datetime] NULL,
	[DueDate] [datetime] NULL,
	[ShipDate] [datetime] NULL)

CREATE CLUSTERED INDEX CI_FactResellerSales_CI ON FactResellerSales_CI (SalesOrderNumber, SalesOrderLineNumber)



SELECT COUNT(*) FROM dbo.FactResellerSales

SET STATISTICS TIME ON

INSERT INTO dbo.FactResellerSales_Heap ( ProductKey ,
                                         OrderDateKey ,
                                         DueDateKey ,
                                         ShipDateKey ,
                                         ResellerKey ,
                                         EmployeeKey ,
                                         PromotionKey ,
                                         CurrencyKey ,
                                         SalesTerritoryKey ,
                                         SalesOrderNumber ,
                                         SalesOrderLineNumber ,
                                         RevisionNumber ,
                                         OrderQuantity ,
                                         UnitPrice ,
                                         ExtendedAmount ,
                                         UnitPriceDiscountPct ,
                                         DiscountAmount ,
                                         ProductStandardCost ,
                                         TotalProductCost ,
                                         SalesAmount ,
                                         TaxAmt ,
                                         Freight ,
                                         CarrierTrackingNumber ,
                                         CustomerPONumber ,
                                         OrderDate ,
                                         DueDate ,
                                         ShipDate )
SELECT ProductKey ,
       OrderDateKey ,
       DueDateKey ,
       ShipDateKey ,
       ResellerKey ,
       EmployeeKey ,
       PromotionKey ,
       CurrencyKey ,
       SalesTerritoryKey ,
       SalesOrderNumber ,
       SalesOrderLineNumber ,
       RevisionNumber ,
       OrderQuantity ,
       UnitPrice ,
       ExtendedAmount ,
       UnitPriceDiscountPct ,
       DiscountAmount ,
       ProductStandardCost ,
       TotalProductCost ,
       SalesAmount ,
       TaxAmt ,
       Freight ,
       CarrierTrackingNumber ,
       CustomerPONumber ,
       OrderDate ,
       DueDate ,
       ShipDate FROM dbo.FactResellerSales


	   
SET STATISTICS TIME ON

INSERT INTO dbo.FactResellerSales_CI ( ProductKey ,
                                         OrderDateKey ,
                                         DueDateKey ,
                                         ShipDateKey ,
                                         ResellerKey ,
                                         EmployeeKey ,
                                         PromotionKey ,
                                         CurrencyKey ,
                                         SalesTerritoryKey ,
                                         SalesOrderNumber ,
                                         SalesOrderLineNumber ,
                                         RevisionNumber ,
                                         OrderQuantity ,
                                         UnitPrice ,
                                         ExtendedAmount ,
                                         UnitPriceDiscountPct ,
                                         DiscountAmount ,
                                         ProductStandardCost ,
                                         TotalProductCost ,
                                         SalesAmount ,
                                         TaxAmt ,
                                         Freight ,
                                         CarrierTrackingNumber ,
                                         CustomerPONumber ,
                                         OrderDate ,
                                         DueDate ,
                                         ShipDate )
SELECT ProductKey ,
       OrderDateKey ,
       DueDateKey ,
       ShipDateKey ,
       ResellerKey ,
       EmployeeKey ,
       PromotionKey ,
       CurrencyKey ,
       SalesTerritoryKey ,
       SalesOrderNumber ,
       SalesOrderLineNumber ,
       RevisionNumber ,
       OrderQuantity ,
       UnitPrice ,
       ExtendedAmount ,
       UnitPriceDiscountPct ,
       DiscountAmount ,
       ProductStandardCost ,
       TotalProductCost ,
       SalesAmount ,
       TaxAmt ,
       Freight ,
       CarrierTrackingNumber ,
       CustomerPONumber ,
       OrderDate ,
       DueDate ,
       ShipDate FROM dbo.FactResellerSales

	   DELETE FROM dbo.FactResellerSales_CI

	   
	   DELETE FROM dbo.FactResellerSales_Heap