-- init
SET NOCOUNT OFF
CREATE DATABASE [DemoDB]

ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT ON
GO
CREATE TABLE dbo.TestIsolationLevels (
EmpID INT NOT NULL,
EmpName VARCHAR(100),
Salary INT,
CONSTRAINT pk_EmpID PRIMARY KEY(EmpID) )
GO
INSERT INTO dbo.TestIsolationLevels 
VALUES 
(2322, 'Drew Brees', 35000),
(2900, 'Mark Ingram', 22000),
(2219, 'Alvin Kamara', 40000),
(2950, 'Cam Jordan', 18000) 
GO

--Start Transaction

BEGIN TRAN
UPDATE  dbo.TestIsolationLevels 
SET     Salary = 25000
WHERE   EmpID = 2900

--ROLLBACK

ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT ON
GO
BEGIN TRAN
UPDATE  dbo.TestIsolationLevels 
SET     Salary = 25000
WHERE   EmpID = 2900

--ROLLBACK


ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET NOCOUNT ON
GO
BEGIN TRAN
UPDATE  dbo.TestIsolationLevels 
SET     EmpSalary = 25000
WHERE   EmpID = 2900


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET NOCOUNT ON
GO
BEGIN TRAN
SELECT  EmpID, EmpName, Salary
FROM    dbo.TestIsolationLevels 
WHERE   EmpID = 2900
WAITFOR DELAY '00:00:10'
SELECT  EmpID, EmpName, Salary
FROM    dbo.TestIsolationLevels 
WHERE   EmpID = 2900
COMMIT


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET NOCOUNT ON
GO
BEGIN TRAN
SELECT  EmpName
FROM    dbo.TestIsolationLevels 
WAITFOR DELAY '00:00:10'
SELECT  EmpName
FROM    dbo.TestIsolationLevels 
COMMIT